const API_BASE="http://localhost:8080/api";
const byId=id=>document.getElementById(id);
async function api(path,options={}){const response=await fetch(API_BASE+path,{headers:{"Content-Type":"application/json"},...options});const data=await response.json();if(!response.ok||data.success===false)throw new Error(data.message||"Request failed");return data}
function updateClock(){const now=new Date();byId("currentDate").textContent=now.toLocaleDateString("en-GB",{weekday:"long",day:"2-digit",month:"short",year:"numeric"});byId("currentTime").textContent=now.toLocaleTimeString([], {hour:"2-digit",minute:"2-digit",second:"2-digit"});byId("dashboardTime").textContent=now.toLocaleTimeString([], {hour:"2-digit",minute:"2-digit",second:"2-digit"});byId("dashboardDate").textContent=now.toLocaleDateString("en-GB",{day:"2-digit",month:"short",year:"numeric"})}
function setFeedback(target,message,type){target.className=`feedback ${type}`;target.textContent=message}
function renderMetrics(data){byId("totalCount").textContent=data.total;byId("occupiedCount").textContent=data.total-data.available;byId("availableCount").textContent=data.available}
function renderSlotChoices(data){const select=byId("entrySlot");select.innerHTML="<option value=\"\">Choose available slot</option>";data.slots.filter(slot=>slot.available).forEach(slot=>{const option=document.createElement("option");option.value=slot.number;option.textContent=`Slot ${slot.number}`;select.appendChild(option)})}
function formatDuration(entryTime){const entered=new Date(entryTime.replace(" ","T"));const minutes=Math.max(0,Math.floor((Date.now()-entered.getTime())/60000));return minutes<60?`${minutes}m`:`${Math.floor(minutes/60)}h ${minutes%60}m`}
async function loadParkedVehicles(){const table=byId("parkedTable");try{const data=await api("/parked");if(!data.vehicles.length){table.innerHTML='<tr><td colspan="6">No vehicles are currently parked.</td></tr>';return}table.innerHTML=data.vehicles.map((vehicle,index)=>`<tr><td>${index+1}</td><td>${vehicle.registration}</td><td><b class="slot-pill green">${vehicle.slot}</b></td><td>${vehicle.entryTime.slice(11,16)}</td><td>${formatDuration(vehicle.entryTime)}</td><td>KSh ${Number(vehicle.amount).toFixed(0)}</td></tr>`).join("")}catch(error){table.innerHTML='<tr><td colspan="6">Unable to load parked vehicles.</td></tr>'}}
async function loadSlots(){const box=byId("availability"),message=byId("availabilityMessage");try{const data=await api("/slots");box.innerHTML="";data.slots.forEach(slot=>{const tile=document.createElement("div");tile.className=`slot ${slot.available?"available":"occupied"}`;tile.innerHTML=`<span>${slot.number}</span><small>${slot.available?"Available":"Occupied"}</small>`;box.appendChild(tile)});renderMetrics(data);renderSlotChoices(data);message.textContent=`${data.available} available of ${data.total} total slots.`}catch(error){message.textContent="Backend not running. Start SmartParkServer first.";message.className="availability-message error"}}
byId("entryForm").addEventListener("submit",async event=>{event.preventDefault();const registration=byId("entryRegistration").value.trim().toUpperCase();try{const data=await api("/entry",{method:"POST",body:JSON.stringify({registration})});setFeedback(byId("entryMessage"),`Vehicle ${data.registration} assigned to slot ${data.slot}.`,"success");event.target.reset();loadSlots();loadParkedVehicles()}catch(error){setFeedback(byId("entryMessage"),error.message,"error")}});
byId("exitForm").addEventListener("submit",async event=>{event.preventDefault();const registration=byId("exitRegistration").value.trim().toUpperCase();try{const data=await api("/exit",{method:"POST",body:JSON.stringify({registration})});byId("exitResult").innerHTML=`<p class="success"><strong>${data.durationMinutes} minutes parked</strong><br>Amount due: KSh ${Number(data.amount).toFixed(2)}</p>`;loadSlots();loadParkedVehicles()}catch(error){byId("exitResult").innerHTML=`<p class="error">${error.message}</p>`}});
updateClock();loadSlots();loadParkedVehicles();setInterval(updateClock,1000);setInterval(()=>{loadSlots();loadParkedVehicles()},5000);
