#include "Database.h"
#include <sqlite3.h>
#include <iostream>
Database::Database():db(nullptr){}Database::~Database(){close();}
bool Database::connect(const std::string&f){sqlite3*c=nullptr;if(sqlite3_open(f.c_str(),&c)!=SQLITE_OK){std::cerr<<"Database connection failed\n";if(c)sqlite3_close(c);return false;}db=c;return createTables();}
bool Database::createTables(){const char*s="CREATE TABLE IF NOT EXISTS vehicles(id INTEGER PRIMARY KEY AUTOINCREMENT,registration TEXT NOT NULL,slot INTEGER NOT NULL,entry_time TEXT NOT NULL,exit_time TEXT,duration_minutes INTEGER DEFAULT 0,amount REAL DEFAULT 0,paid INTEGER DEFAULT 0);";char*e=nullptr;int r=sqlite3_exec((sqlite3*)db,s,nullptr,nullptr,&e);if(r!=SQLITE_OK){sqlite3_free(e);return false;}return true;}
bool Database::saveVehicle(const std::string&r,int slot){const char*s="INSERT INTO vehicles(registration,slot,entry_time,paid) VALUES(?,?,datetime('now','localtime'),0);";sqlite3_stmt*q=nullptr;if(sqlite3_prepare_v2((sqlite3*)db,s,-1,&q,nullptr)!=SQLITE_OK)return false;sqlite3_bind_text(q,1,r.c_str(),-1,SQLITE_TRANSIENT);sqlite3_bind_int(q,2,slot);bool ok=sqlite3_step(q)==SQLITE_DONE;sqlite3_finalize(q);return ok;}
bool Database::findActiveVehicle(const std::string&r,VehicleRecord&v){const char*s="SELECT id,registration,slot,entry_time,IFNULL(exit_time,''),duration_minutes,amount,paid FROM vehicles WHERE registration=? AND exit_time IS NULL ORDER BY id DESC LIMIT 1;";sqlite3_stmt*q=nullptr;if(sqlite3_prepare_v2((sqlite3*)db,s,-1,&q,nullptr)!=SQLITE_OK)return false;sqlite3_bind_text(q,1,r.c_str(),-1,SQLITE_TRANSIENT);bool ok=false;if(sqlite3_step(q)==SQLITE_ROW){v.id=sqlite3_column_int(q,0);v.registration=(const char*)sqlite3_column_text(q,1);v.slot=sqlite3_column_int(q,2);v.entryTime=(const char*)sqlite3_column_text(q,3);v.exitTime=(const char*)sqlite3_column_text(q,4);v.durationMinutes=sqlite3_column_int(q,5);v.amount=sqlite3_column_double(q,6);v.paid=sqlite3_column_int(q,7)!=0;ok=true;}sqlite3_finalize(q);return ok;}
bool Database::findUnpaidVehicle(const std::string&r,VehicleRecord&v){const char*s="SELECT id,registration,slot,entry_time,IFNULL(exit_time,''),duration_minutes,amount,paid FROM vehicles WHERE registration=? AND exit_time IS NOT NULL AND paid=0 ORDER BY id DESC LIMIT 1;";sqlite3_stmt*q=nullptr;if(sqlite3_prepare_v2((sqlite3*)db,s,-1,&q,nullptr)!=SQLITE_OK)return false;sqlite3_bind_text(q,1,r.c_str(),-1,SQLITE_TRANSIENT);bool ok=false;if(sqlite3_step(q)==SQLITE_ROW){v.id=sqlite3_column_int(q,0);v.registration=(const char*)sqlite3_column_text(q,1);v.slot=sqlite3_column_int(q,2);v.entryTime=(const char*)sqlite3_column_text(q,3);v.exitTime=(const char*)sqlite3_column_text(q,4);v.durationMinutes=sqlite3_column_int(q,5);v.amount=sqlite3_column_double(q,6);v.paid=sqlite3_column_int(q,7)!=0;ok=true;}sqlite3_finalize(q);return ok;}
bool Database::updateExit(const std::string&r,const std::string&t,int m,double a){const char*s="UPDATE vehicles SET exit_time=?,duration_minutes=?,amount=? WHERE id=(SELECT id FROM vehicles WHERE registration=? AND exit_time IS NULL ORDER BY id DESC LIMIT 1);";sqlite3_stmt*q=nullptr;if(sqlite3_prepare_v2((sqlite3*)db,s,-1,&q,nullptr)!=SQLITE_OK)return false;sqlite3_bind_text(q,1,t.c_str(),-1,SQLITE_TRANSIENT);sqlite3_bind_int(q,2,m);sqlite3_bind_double(q,3,a);sqlite3_bind_text(q,4,r.c_str(),-1,SQLITE_TRANSIENT);bool ok=sqlite3_step(q)==SQLITE_DONE&&sqlite3_changes((sqlite3*)db)>0;sqlite3_finalize(q);return ok;}
bool Database::markPaid(const std::string&r){const char*s="UPDATE vehicles SET paid=1 WHERE id=(SELECT id FROM vehicles WHERE registration=? AND exit_time IS NOT NULL AND paid=0 ORDER BY id DESC LIMIT 1);";sqlite3_stmt*q=nullptr;if(sqlite3_prepare_v2((sqlite3*)db,s,-1,&q,nullptr)!=SQLITE_OK)return false;sqlite3_bind_text(q,1,r.c_str(),-1,SQLITE_TRANSIENT);bool ok=sqlite3_step(q)==SQLITE_DONE&&sqlite3_changes((sqlite3*)db)>0;sqlite3_finalize(q);return ok;}
bool Database::getAllActiveVehicles(std::vector<VehicleRecord>&a){a.clear();const char*s="SELECT id,registration,slot,entry_time,IFNULL(exit_time,''),duration_minutes,amount,paid FROM vehicles WHERE exit_time IS NULL ORDER BY slot;";sqlite3_stmt*q=nullptr;if(sqlite3_prepare_v2((sqlite3*)db,s,-1,&q,nullptr)!=SQLITE_OK)return false;while(sqlite3_step(q)==SQLITE_ROW){VehicleRecord v;v.id=sqlite3_column_int(q,0);v.registration=(const char*)sqlite3_column_text(q,1);v.slot=sqlite3_column_int(q,2);v.entryTime=(const char*)sqlite3_column_text(q,3);v.exitTime=(const char*)sqlite3_column_text(q,4);v.durationMinutes=sqlite3_column_int(q,5);v.amount=sqlite3_column_double(q,6);v.paid=sqlite3_column_int(q,7)!=0;a.push_back(v);}sqlite3_finalize(q);return true;}
void Database::close(){if(db){sqlite3_close((sqlite3*)db);db=nullptr;}}